# Generated by Django 4.2.3 on 2023-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
