# Generated by Django 4.2.3 on 2023-09-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_location_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='active',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Reservado'),
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe')),
                ('currency', models.CharField(choices=[('$Bs', 'Bolivianos'), ('$Usd', 'Dolares')], default='$Usd', max_length=5)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='taller.customer', verbose_name='Cliente')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='taller.employee', verbose_name='Vendedor')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='taller.vehicle', verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
