# Generated by Django 4.2.3 on 2023-09-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_remove_state_active_vehicle_reserved_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
